using SQL2Graph.Models;
using System.Text;

namespace SQL2Graph.Services;

/// <summary>
/// Service for graph model operations and Cypher generation
/// </summary>
public class GraphModelService
{
    private readonly ILogger<GraphModelService> _logger;

    public GraphModelService(ILogger<GraphModelService> logger)
    {
        _logger = logger;
    }

    /// <summary>
    /// Generates Cypher DDL for creating constraints and indexes
    /// </summary>
    public string GenerateCypherDDL(GraphModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// ===== Neo4j Graph Model DDL =====");
        sb.AppendLine("// Generated by SQL2Graph");
        sb.AppendLine();

        // Create constraints for node keys
        foreach (var node in model.Nodes)
        {
            var keyProp = node.Properties.FirstOrDefault(p => p.IsKey);
            if (keyProp != null)
            {
                sb.AppendLine($"// Constraint for {node.Label}");
                sb.AppendLine($"CREATE CONSTRAINT {node.Label.ToLower()}_id IF NOT EXISTS");
                sb.AppendLine($"FOR (n:{node.Label})");
                sb.AppendLine($"REQUIRE n.{keyProp.GraphProperty} IS UNIQUE;");
                sb.AppendLine();
            }
        }

        // Create indexes for frequently queried properties
        foreach (var node in model.Nodes)
        {
            var nonKeyProps = node.Properties.Where(p => !p.IsKey).Take(2);
            foreach (var prop in nonKeyProps)
            {
                if (prop.GraphProperty.Contains("name", StringComparison.OrdinalIgnoreCase) ||
                    prop.GraphProperty.Contains("email", StringComparison.OrdinalIgnoreCase))
                {
                    sb.AppendLine($"CREATE INDEX {node.Label.ToLower()}_{prop.GraphProperty.ToLower()} IF NOT EXISTS");
                    sb.AppendLine($"FOR (n:{node.Label})");
                    sb.AppendLine($"ON (n.{prop.GraphProperty});");
                    sb.AppendLine();
                }
            }
        }

        return sb.ToString();
    }

    /// <summary>
    /// Generates Cypher ETL script for data migration
    /// </summary>
    public string GenerateCypherETL(GraphModel model, SqlSchema schema)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// ===== Neo4j Data Migration Script =====");
        sb.AppendLine("// Generated by SQL2Graph");
        sb.AppendLine("// Note: Adjust LOAD CSV paths to your export location");
        sb.AppendLine();

        // Generate node creation statements
        foreach (var node in model.Nodes)
        {
            sb.AppendLine($"// Create {node.Label} nodes from {node.SourceTable}");
            var tableName = node.SourceTable.Contains(".") ? node.SourceTable.Replace(".", "_") : $"dbo_{node.SourceTable}";
            sb.AppendLine($"LOAD CSV WITH HEADERS FROM 'file:///{tableName}.csv' AS row");
            sb.Append($"CREATE (n:{node.Label} {{");
            
            var propStrings = node.Properties.Select(p => 
                $"{p.GraphProperty}: row.{p.SqlColumn}");
            sb.Append(string.Join(", ", propStrings));
            
            sb.AppendLine("});");
            sb.AppendLine();
        }

        // Generate relationship creation statements
        foreach (var rel in model.Relationships)
        {
            var fromNode = model.Nodes.FirstOrDefault(n => n.Label == rel.FromNode);
            var toNode = model.Nodes.FirstOrDefault(n => n.Label == rel.ToNode);
            
            if (fromNode == null || toNode == null) continue;

            var fromKey = fromNode.Properties.FirstOrDefault(p => p.IsKey)?.GraphProperty ?? "id";
            var toKey = toNode.Properties.FirstOrDefault(p => p.IsKey)?.GraphProperty ?? "id";

            sb.AppendLine($"// Create {rel.Type} relationships");
            var relTableName = rel.SourceTable.Contains(".") ? rel.SourceTable.Replace(".", "_") : $"dbo_{rel.SourceTable}";
            sb.AppendLine($"LOAD CSV WITH HEADERS FROM 'file:///{relTableName}.csv' AS row");
            sb.AppendLine($"MATCH (from:{rel.FromNode} {{{fromKey}: row.from_id}})");
            sb.AppendLine($"MATCH (to:{rel.ToNode} {{{toKey}: row.to_id}})");
            
            if (rel.Properties.Count > 0)
            {
                sb.Append($"CREATE (from)-[r:{rel.Type} {{");
                var propStrings = rel.Properties.Select(p => 
                    $"{p.GraphProperty}: row.{p.SqlColumn}");
                sb.Append(string.Join(", ", propStrings));
                sb.AppendLine("}]->(to);");
            }
            else
            {
                sb.AppendLine($"CREATE (from)-[:{rel.Type}]->(to);");
            }
            sb.AppendLine();
        }

        return sb.ToString();
    }

    /// <summary>
    /// Converts graph model to JSON for visualization
    /// </summary>
    public object ToVisualizationData(GraphModel model)
    {
        return new
        {
            nodes = model.Nodes.Select(n => new
            {
                id = n.Label,
                label = n.Label,
                sourceTable = n.SourceTable,
                description = n.Description,
                properties = n.Properties,
                color = n.Color,
                x = n.X,
                y = n.Y
            }),
            edges = model.Relationships.Select(r => new
            {
                id = $"{r.FromNode}_{r.Type}_{r.ToNode}",
                source = r.FromNode,
                target = r.ToNode,
                type = r.Type,
                sourceTable = r.SourceTable,
                description = r.Description,
                isJoinTable = r.IsJoinTable,
                properties = r.Properties
            })
        };
    }
}
